insert into users (username) values ('fido');
insert into users (username) values ('bandit');

INSERT INTO movies ( title, user_id ) VALUES ('War Games',1);

-- INSERT INTO movies ( popularity, poster_path, movie_id, backdrop_path, title, vote_average, overview, release_date, user_id ) VALUES (79.876, 'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 299536, 'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg', 'War Games', 8.3, 'As the Avengers and their allies have continued to protect the', '2018-04-25', 1);

-- INSERT INTO watchlist ( popularity, poster_path, movie_id, backdrop_path, title, vote_average, overview, release_date, user_id ) VALUES (79.876, 'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 299536, 'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg', 'War Games', 8.3, 'As the Avengers and their allies have continued to protect the', '2018-04-25', 1);

-- INSERT INTO movies ( popularity, vote_count, video, poster_path, movie_id, adult, backdrop_path, original_language, original_title, genre_ids, title, vote_average, overview, release_date, user_id ) VALUES (79.876,18610,false,'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',299536,false,'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg','en','Sleepless in Seattle',24,'Sleepless in Seattle',8.3,'As the Avengers and their allies have continued to protect the', '2018-04-25', 2 );
-- INSERT INTO movies ( popularity, vote_count, video, poster_path, movie_id, adult, backdrop_path, original_language, original_title, genre_ids, title, vote_average, overview, release_date, user_id ) VALUES (79.876,18610,false,'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',299536,false,'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg','en','Detecitve Pikachu',24,'Detecitve Pikachu',8.3,'As the Avengers and their allies have continued to protect the', '2018-04-25', 1 );
-- INSERT INTO movies ( popularity, vote_count, video, poster_path, movie_id, adult, backdrop_path, original_language, original_title, genre_ids, title, vote_average, overview, release_date, user_id ) VALUES (79.876,18610,false,'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',299536,false,'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg','en','Spirited Away', 24,'Spirited Away',8.3,'As the Avengers and their allies have continued to protect the', '2018-04-25', 1 );
-- INSERT INTO movies ( popularity, vote_count, video, poster_path, movie_id, adult, backdrop_path, original_language, original_title, genre_ids, title, vote_average, overview, release_date, user_id ) VALUES (79.876,18610,false,'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',299536,false,'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg','en','Howls Moving Castle',24,'Howls Moving Castle',8.3,'As the Avengers and their allies have continued to protect the', '2018-04-25', 2 );
-- INSERT INTO movies ( popularity, vote_count, video, poster_path, movie_id, adult, backdrop_path, original_language, original_title, genre_ids, title, vote_average, overview, release_date, user_id ) VALUES (79.876,18610,false,'https://image.tmdb.org/t/p/w200/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',299536,false,'https://image.tmdb.org/t/p/w200/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg','en','Cowboy Bebop',24,'Cowboy Bebop',8.3,'As the Avengers and their allies have continued to protect the', '2018-04-25', 2 );